
spring:
  thymeleaf:
    suffix: .html

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
mybatis:
  type-aliases-package: com.example.demo.domain

server:
  port: 8088